In [1]:
%load_ext autoreload
%autoreload 3

In [2]:
import sys

from pytil.tests.imports import *

In [3]:
from typing import Type

my_spec = (
    ('data', nb.int64[:]),
    ('other', nb.int64[:]),
)


@jitclass(my_spec)
class MyClass:
    def __init__(self, data, other):
        self.data = np.asarray(data, dtype=np.int64)
        self.other = np.asarray(other, dtype=np.int64)

    def sum(self):
        print("MyClass original")
        return self.data.sum()

    def head(self):
        return self.data[0], self.other[0]

    def calc(self, x):
        return


my = MyClass(data=[4], other=[0])
my.head()

(4, 0)

In [ ]:
special3 = 2433
time.sleep(3)

In [47]:
match np.inf:
    case 6:
        print("6")
    case Number():
        print("Number")
    case _:
        print('default')

Number


In [10]:
from collections import deque


@closure
def check_knight_norm():
    bound = 100000
    seen = {(0, 0): 0}
    assert seen[0, 0] == get_knight_norm((0, 0))
    frontier = deque([(0, 0)])
    for i in range(bound):
        x, y = frontier.popleft()
        for dx, dy in [(2, 1), (1, 2), (-2, -1), (-1, -2), (-2, 1), (-1, 2), (2, -1), (1, -2)]:
            x1, y1 = x + dx, y + dy
            if -bound <= x1 <= bound and -bound <= y1 < bound:
                if (x1, y1) not in seen:
                    seen[x1, y1] = seen[x, y] + 1
                    assert seen[x1, y1] == get_knight_norm((x1, y1)), print(
                        f'{x1, y1}: {seen[x, y] + 1} but {get_knight_norm((x1, y1)) = }'
                    )
                    frontier.append((x1, y1))

In [149]:
halfknight_neighbors = ((2, 1), (-1, 2), (-2, -1), (1, -2))
knight_neighbors = halfknight_neighbors + ((-2, 1), (1, 2), (2, -1), (-1, -2))
knight_3_1_neighbors = ((3, 1), (1, 3), (-3, -1), (-1, -3), (-3, 1), (-1, 3), (3, -1), (1, -3))
knight_3_2_neighbors = ((3, 2), (2, 3), (-3, -2), (-2, -3), (-3, 2), (-2, 3), (3, -2), (2, -3))

cardinal_neighbors = ((1, 0), (0, 1), (-1, 0), (0, -1))
ordinal_neighbors = ((1, 1), (1, -1), (-1, 1), (-1, -1))
cardinal2_neighbors = ((2, 0), (0, 2), (-2, 0), (0, -2))
ordinal2_neighbors = ((2, 2), (2, -2), (-2, 2), (-2, -2))
cardinal3_neighbors = ((3, 0), (0, 3), (-3, 0), (0, -3))
ordinal3_neighbors = ((3, 3), (3, -3), (-3, 3), (-3, -3))
eight_neighbors = cardinal_neighbors + ordinal_neighbors
eight2_neighbors = cardinal2_neighbors + ordinal2_neighbors
eight3_neighbors = cardinal3_neighbors + ordinal3_neighbors
knight_neighbors = ((2, 1), (1, 2), (-1, 2), (-2, 1), (-2, -1), (-1, -2), (1, -2), (2, -1))
knight_3_2_neighbors = ((3, 2), (2, 3), (-3, -2), (-2, -3), (-3, 2), (-2, 3), (3, -2), (2, -3))
knight_4_1_neighbors = ((4, 1), (1, 4), (-4, -1), (-1, -4), (-4, 1), (-1, 4), (4, -1), (1, -4))
knight_4_3_neighbors = ((4, 3), (3, 4), (-4, -3), (-3, -4), (-4, 3), (-3, 4), (4, -3), (3, -4))
knight_5_2_neighbors = ((5, 2), (2, 5), (-5, -2), (-2, -5), (-5, 2), (-2, 5), (5, -2), (2, -5))
knight_5_4_neighbors = ((5, 4), (4, 5), (-5, -4), (-4, -5), (-5, 4), (-4, 5), (5, -4), (4, -5))

the_neighbors = knight_5_4_neighbors


@closure
def check_knight_can_reach():
    bound = 30

    def search(x, y):
        seen = {(x, y): 0}
        frontier = deque([(x, y)])
        while frontier:
            x, y = frontier.popleft()
            for dx, dy in the_neighbors:
                x1, y1 = x + dx, y + dy
                if 0 <= x1 < bound and 0 <= y1 < bound:
                    if (x1, y1) not in seen:
                        seen[x1, y1] = seen[x, y] + 1
                        frontier.append((x1, y1))
        return seen

    for i in range(bound):
        for j in range(bound):
            seen = search(i, j)
            reached = set(seen)
            everything = set(product(range(bound), range(bound)))
            assert reached == everything, f'({i}, {j}): {len(everything - reached) = }'

In [12]:
params = False
np.full((1, 1, 3), ((0, 255, 0) if params else (255, 0, 0)), dtype=np.uint8)

array([[[255,   0,   0]]], dtype=uint8)

In [ ]:
@njit
def hi(x):
    match x:
        case float():
            return 'float'
        case int():
            return 'int'
        case _:
            return 'other'


print(hi(1))

UnsupportedBytecodeError: Use of unsupported opcode (MATCH_CLASS) found. Raised from /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_20298/1677034510.py (4)

In [ ]:
ArrayHeap1 = get_array_heap_1d_items_jitclass(nb.int64)
ArrayTreap1 = get_array_treap_1d_items_jitclass(nb.int64)


@njit
def hi(flag):
    if flag:
        heap = ArrayHeap1(10, 1)
        data = heap
    else:
        # assert False
        treap = ArrayTreap1(10, 1)
        data = treap
    for i in range(10):
        if flag:
            data.heappush((i,))
        else:
            data.insert((i,))
    return data[0]


hi(False)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify instance.jitclass.ArrayHeap1#14d9cf380<capacity:int64,item_size:int64,size:int64,heap:array(int64, 2d, A)> and instance.jitclass.ArrayTreap1#14d9ccbf0<capacity:int64,item_size:int64,size:int64,root:int64,data:array(int64, 2d, A),priorities:array(int64, 1d, A),left:array(int64, 1d, A),right:array(int64, 1d, A),parent:array(int64, 1d, A),free_list:array(int64, 1d, A),free_list_top:int64,subtree_size:array(int64, 1d, A)> for 'data.2', defined at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_49527/3263611359.py (16)

File "../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_49527/3263611359.py", line 16:
<source missing, REPL/exec in use?>

During: typing of assignment at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_49527/3263611359.py (16)

File "../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_49527/3263611359.py", line 16:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
# These still allocate some memory, are not most efficient


@njit
def float64_to_int64_bitcast(x):
    return np.int64(np.asarray(x).view(np.int64))


@njit
def int64_to_float64_bitcast(x):
    return np.float64(np.asarray(x).view(np.float64))

In [40]:
i = 1.0
f = float64_to_int64_bitcast(1.0)
print(f)
i1 = int64_to_float64_bitcast(f)
i1

4607182418800017408


1.0

In [ ]:
from numba.core.registry import CPUDispatcher


def dump_machine_code(fn):
    if isinstance(fn, CPUDispatcher):
        cres = fn.overloads[list(fn.overloads.keys())[0]]
        print(cres.library.get_asm_str())

In [44]:
dump_machine_code(int64_to_float64_bitcast)

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 15, 0
	.globl	__ZN8__main__24int64_to_float64_bitcastB3v26B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEx
	.p2align	4, 0x90
__ZN8__main__24int64_to_float64_bitcastB3v26B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEx:
	.cfi_startproc
	pushq	%r15
	.cfi_def_cfa_offset 16
	pushq	%r14
	.cfi_def_cfa_offset 24
	pushq	%r13
	.cfi_def_cfa_offset 32
	pushq	%r12
	.cfi_def_cfa_offset 40
	pushq	%rbx
	.cfi_def_cfa_offset 48
	subq	$80, %rsp
	.cfi_def_cfa_offset 128
	.cfi_offset %rbx, -48
	.cfi_offset %r12, -40
	.cfi_offset %r13, -32
	.cfi_offset %r14, -24
	.cfi_offset %r15, -16
	movq	%rdx, %r12
	movq	%rsi, %r14
	movq	%rdi, %r15
	movabsq	$_NRT_MemInfo_alloc_aligned, %rax
	movl	$8, %edi
	movl	$32, %esi
	callq	*%rax
	testq	%rax, %rax
	je	LBB0_1
	movq	%rax, %rbx
	movq	24(%rax), %r13
	movq	%r12, (%r13)
	movabsq	$_NRT_incref, %r12
	movq	%rax, %rdi
	callq	*%r12
	movq	$0, 24(%rsp)
	movq	%rbx, %rdi
	callq	*%r12
	movq	%rbx, 40(%rsp)
	movq	$0, 48(%

In [3]:
# These work the best
from numba.extending import intrinsic


@intrinsic
def bitcast_float64_to_int64(typingctx, x):
    sig = nb.int64(x)

    def codegen(context, builder, signature, args):
        [x_val] = args
        return builder.bitcast(x_val, context.get_value_type(nb.int64))

    return sig, codegen


@intrinsic
def bitcast_int64_to_float64(typingctx, x):
    sig = nb.float64(x)

    def codegen(context, builder, signature, args):
        [x_val] = args
        return builder.bitcast(x_val, context.get_value_type(nb.float64))

    return sig, codegen

In [11]:
@njit
def test():
    i = bitcast_float64_to_int64(3.141592653589793)
    f = bitcast_int64_to_float64(i)
    return i, f


print(test()[1])

3.141592653589793


In [54]:
dump_machine_code(bitcast_float64_to_int64)

In [55]:
@njit
def test_bitcast(x):
    return bitcast_float64_to_int64(x)


test_bitcast.compile((float64,))

<function __main__._Closure.test_bitcast>

In [59]:
print(test_bitcast.inspect_asm((float64,)))

	.section	__TEXT,__text,regular,pure_instructions
	.build_version macos, 15, 0
	.globl	__ZN8__main__12test_bitcastB3v32B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEd
	.p2align	4, 0x90
__ZN8__main__12test_bitcastB3v32B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEd:
	vmovsd	%xmm0, (%rdi)
	xorl	%eax, %eax
	retq

	.globl	__ZN7cpython8__main__12test_bitcastB3v32B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEd
	.p2align	4, 0x90
__ZN7cpython8__main__12test_bitcastB3v32B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEd:
	.cfi_startproc
	pushq	%rbx
	.cfi_def_cfa_offset 16
	subq	$32, %rsp
	.cfi_def_cfa_offset 48
	.cfi_offset %rbx, -16
	movq	%rsi, %rdi
	movabsq	$_.const.test_bitcast, %rsi
	movabsq	$_PyArg_UnpackTuple, %r9
	xorl	%ebx, %ebx
	leaq	24(%rsp), %r8
	movl	$1, %edx
	movl	$1, %ecx
	xorl	%eax, %eax
	callq	*%r9
	testl	%eax, %eax
	je	LBB1_4
	movabsq	$__ZN08NumbaEnv8__main__12test_bitcastB3v32B38c8tJTIeFIjxB2IKSgI4CrvQClQZ6FczSBAA_3dEd, %rax
	cmpq	$0, (%rax)
	je	LBB1_5
	movq	24(%rsp), %rdi
	movabsq	$_PyNumber_Fl

In [ ]:
Item = namedtuple('Item', 'value index')


@njit
def hi(value):
    item = Item(value=value, index=0)
    a = np.empty(2, dtype=np.int64)
    a[:] = item
    return a


hi(60)

array([60,  0])

In [ ]:
Item = namedtuple('Item', 'value index')


@njit
def hi(a):
    item = Item(*a)
    return item


hi(np.asarray((60, 0)))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
*args in function call should be a tuple, got array(int64, 1d, C)
During: resolving callee type: class(<class '__main__.Item'>)
During: typing of call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_55190/1634974160.py (4)


File "../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_55190/1634974160.py", line 4:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
@njit
def hi():
    return int(np.nan)


hi()

0

In [ ]:
1 / (np.arctan2(1, 4095) - np.arctan2(1, 4094))

np.float64(-16764931.000000536)

In [ ]:
def hi():
    return 5, 8, 'what'


a, b, c, *_ = hi()
_

[]

In [19]:
isinstance((5, 5), (int, float))

False

In [34]:
starts_coordinates = [(8, 3), (10.5, 9.5), (100, 1)]
starts_grid_coordinates = []
for coordinates in starts_coordinates:
    assert isinstance(coordinates, tuple) and len(coordinates) == 2
    # assert 0 <= coordinates[0] < m and 0 <= coordinates[1] < n
    grid_coordinates_grid = []
    for coordinate in coordinates:
        grid_coordinate_set = set()
        if isinstance(coordinate, float):
            assert coordinate % 1.0 != 0.0, "Use int instead of float for perfectly integer coordinates"
        grid_coordinate_set.add(math.floor(coordinate))
        grid_coordinate_set.add(math.ceil(coordinate))
        grid_coordinates_grid.append(tuple(grid_coordinate_set))
    start_grid_coordinates = list(product(*grid_coordinates_grid))
    starts_grid_coordinates.extend(start_grid_coordinates)
starts_grid_coordinates

[(8, 3), (10, 9), (10, 10), (11, 9), (11, 10), (100, 1)]

In [38]:
shortlist = 'four eight knight cross2 target star2 corner_square sixteen knight_3_2 knight_4_1'.split()
shortlist += 'four_knight eight_knight fence corner four_ordinal2 eight_ordinal2 diamond2 cross3 star3'.split()
len(shortlist)

19

In [ ]:
isinstance(math.prod([5, 6]), int)

True

In [ ]:
@njit
def hi():
    return math.prod([5, 6])


hi()

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'prod' of type Module(<module 'math' from '/Users/michaelyu/anaconda3/lib/python3.12/lib-dynload/math.cpython-312-darwin.so'>)

File "../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_84930/566828613.py", line 3:
<source missing, REPL/exec in use?>

During: typing of get attribute at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_84930/566828613.py (3)

File "../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_84930/566828613.py", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [38]:
np.arctan2(0, 0)

np.float64(0.0)

In [ ]:
def iterate_over_param_combinations_wrong(param_grid):
    # AI wrote this, but it's wrong
    # Keep track of original param order
    param_order = []
    processed_params = {}
    grouped_params = {}

    # Process each key in the param grid while preserving order
    for key in param_grid:
        if isinstance(key, tuple):
            grouped_params[key] = param_grid[key]
            param_order.append(key)
        else:
            processed_params[key] = param_grid[key]
            param_order.append(key)

    # Generate all combinations of individual parameters
    individual_keys = list(processed_params.keys())
    individual_values = list(processed_params.values())
    individual_combinations = product(*individual_values)

    # Generate combinations including grouped parameters
    grouped_keys = list(grouped_params.keys())
    grouped_values = list(grouped_params.values())

    # Combine individual and grouped parameters
    for ind_values in individual_combinations:
        ind_params = {individual_keys[i]: ind_values[i] for i in range(len(individual_keys))}

        if grouped_params:
            # If there are grouped parameters, combine with individual parameters
            for grouped_value_combinations in product(*grouped_values):
                result = {}

                # Fill in values in the original order
                for orig_key in param_order:
                    if isinstance(orig_key, tuple):
                        # Handle grouped parameters
                        group_idx = grouped_keys.index(orig_key)
                        group_values = grouped_value_combinations[group_idx]
                        for k, v in zip(orig_key, group_values):
                            result[k] = v
                    else:
                        # Handle individual parameters
                        result[orig_key] = ind_params[orig_key]

                yield result
        else:
            # If no grouped parameters, just yield individual parameters
            result = {}
            for orig_key in param_order:
                result[orig_key] = ind_params[orig_key]
            yield result

In [29]:
def iterate_over_param_combinations(param_grid):
    keys = list(param_grid.keys())
    values = list(param_grid.values())
    for values_tuple in product(*values):
        result = {}
        for i in range(len(keys)):
            if isinstance(keys[i], str):
                result[keys[i]] = values_tuple[i]
            elif isinstance(keys[i], tuple):
                group_values = values_tuple[i]
                for j, k in enumerate(keys[i]):
                    result[k] = group_values[j]
        yield result

In [30]:
param_grid = {
    "multiply_param0": ["value00", "value01"],
    ("together_param0", "together_param1"): [
        ("together_value00", "together_value01"),
        ("together_value10", "together_value11"),
    ],
    "multiply_param1": ["value10", "value11"],
}
list(iterate_over_param_combinations(param_grid))

[{'multiply_param0': 'value00',
  'together_param0': 'together_value00',
  'together_param1': 'together_value01',
  'multiply_param1': 'value10'},
 {'multiply_param0': 'value00',
  'together_param0': 'together_value00',
  'together_param1': 'together_value01',
  'multiply_param1': 'value11'},
 {'multiply_param0': 'value00',
  'together_param0': 'together_value10',
  'together_param1': 'together_value11',
  'multiply_param1': 'value10'},
 {'multiply_param0': 'value00',
  'together_param0': 'together_value10',
  'together_param1': 'together_value11',
  'multiply_param1': 'value11'},
 {'multiply_param0': 'value01',
  'together_param0': 'together_value00',
  'together_param1': 'together_value01',
  'multiply_param1': 'value10'},
 {'multiply_param0': 'value01',
  'together_param0': 'together_value00',
  'together_param1': 'together_value01',
  'multiply_param1': 'value11'},
 {'multiply_param0': 'value01',
  'together_param0': 'together_value10',
  'together_param1': 'together_value11',
  'm

In [31]:
param_grid = {
    "multiply_param0": ["value00", "value01"],
    "multiply_param1": ["value10", "value11"],
    "multiply_param2": ["value20", "value21"],
}
list(iterate_over_param_combinations(param_grid))

[{'multiply_param0': 'value00',
  'multiply_param1': 'value10',
  'multiply_param2': 'value20'},
 {'multiply_param0': 'value00',
  'multiply_param1': 'value10',
  'multiply_param2': 'value21'},
 {'multiply_param0': 'value00',
  'multiply_param1': 'value11',
  'multiply_param2': 'value20'},
 {'multiply_param0': 'value00',
  'multiply_param1': 'value11',
  'multiply_param2': 'value21'},
 {'multiply_param0': 'value01',
  'multiply_param1': 'value10',
  'multiply_param2': 'value20'},
 {'multiply_param0': 'value01',
  'multiply_param1': 'value10',
  'multiply_param2': 'value21'},
 {'multiply_param0': 'value01',
  'multiply_param1': 'value11',
  'multiply_param2': 'value20'},
 {'multiply_param0': 'value01',
  'multiply_param1': 'value11',
  'multiply_param2': 'value21'}]

In [32]:
param_grid = {
    'p': ['altered'],
    # starts_count=[100],
    # previous_count=[1, 2, 5, 10, 50],
    # cloudy=[0.0, 0.05, 0.2, 1.0, 2.0],
    # force_grow=[0.0, 0.001, 0.01, 0.1, 1.0],
    # original_start=[False, True],
    # initial_behavior=['average'],
    'altered_p': [1.0],
    'altered_combiner': ['sum'],
    ('altered_pretransform', 'altered_posttransform'): [
        ('identity', 'identity'),
        ('identity', 'bit_count'),
        ('bit_count', 'identity'),
        ('identity', 'two_adic_order'),
        ('two_adic_order', 'identity'),
        ('identity', 'two_adic_power'),
        ('two_adic_power', 'identity'),
        ('identity', 'two_adic_norm'),
        ('two_adic_norm', 'identity'),
    ],
    'select_priority': [0, -1],
    'search_by': ['similarity', 'value'],
    'connectivity': ['placeholder'],
}
list(iterate_over_param_combinations(param_grid))

[{'p': 'altered',
  'altered_p': 1.0,
  'altered_combiner': 'sum',
  'altered_pretransform': 'identity',
  'altered_posttransform': 'identity',
  'select_priority': 0,
  'search_by': 'similarity',
  'connectivity': 'placeholder'},
 {'p': 'altered',
  'altered_p': 1.0,
  'altered_combiner': 'sum',
  'altered_pretransform': 'identity',
  'altered_posttransform': 'identity',
  'select_priority': 0,
  'search_by': 'value',
  'connectivity': 'placeholder'},
 {'p': 'altered',
  'altered_p': 1.0,
  'altered_combiner': 'sum',
  'altered_pretransform': 'identity',
  'altered_posttransform': 'identity',
  'select_priority': -1,
  'search_by': 'similarity',
  'connectivity': 'placeholder'},
 {'p': 'altered',
  'altered_p': 1.0,
  'altered_combiner': 'sum',
  'altered_pretransform': 'identity',
  'altered_posttransform': 'identity',
  'select_priority': -1,
  'search_by': 'value',
  'connectivity': 'placeholder'},
 {'p': 'altered',
  'altered_p': 1.0,
  'altered_combiner': 'sum',
  'altered_pretra

In [ ]:
@njit
def hi():
    a = np.asarray([1, 2])
    b = np.asarray([2, 1])
    return a / b


hi()

array([0.5, 2. ])

In [ ]:
from pytil.new_utility import identity

identity.__name__

'identity'

In [25]:
floor

<function math.floor(x, /)>

In [38]:
a = 1e15 + 1.123456789
b = 1e15 - tau

In [40]:
a - b

7.375

In [41]:
(a - b) % tau

1.0918146928204138

In [42]:
(a % tau - b % tau) % tau

1.0918146928204138

In [ ]:
# revision 1

import math
import numpy as np

# true tau
tau = 2 * math.pi


# function to compute true remainder using high-precision arithmetic
def true_mod(a, b, tau):
    # Use Python's arbitrary-precision integers/fractions for exact difference
    return (a - b) % tau


# small difference
delta = 1e-8

# test a values spanning several orders of magnitude
a_values = np.logspace(1, 20, num=20)  # 10^1 to 10^20

# store errors
error_direct = []
error_mod = []

for a in a_values:
    b = a - delta

    # true remainder using Python float subtraction
    # (for very large numbers, use decimal module for higher accuracy)
    R_true = (a - b) % tau  # mathematically 1 % tau = 1

    # method 1: direct subtraction modulo tau
    R1 = (a - b) % tau
    err1 = abs(R1 - R_true)
    error_direct.append(err1)

    # method 2: pre-reduce a and b modulo tau
    a_mod = a % tau
    b_mod = b % tau
    R2 = (a_mod - b_mod) % tau
    err2 = abs(R2 - R_true)
    error_mod.append(err2)

# display results
print("a\t\tError direct\tError pre-mod")
for a, e1, e2 in zip(a_values, error_direct, error_mod):
    print(f"{a:.1e}\t{e1:.3e}\t\t{e2:.3e}")

a		Error direct	Error pre-mod
1.0e+01	0.000e+00		0.000e+00
1.0e+02	0.000e+00		0.000e+00
1.0e+03	0.000e+00		0.000e+00
1.0e+04	0.000e+00		0.000e+00
1.0e+05	0.000e+00		0.000e+00
1.0e+06	0.000e+00		0.000e+00
1.0e+07	0.000e+00		0.000e+00
1.0e+08	0.000e+00		0.000e+00
1.0e+09	0.000e+00		0.000e+00
1.0e+10	0.000e+00		0.000e+00
1.0e+11	0.000e+00		0.000e+00
1.0e+12	0.000e+00		0.000e+00
1.0e+13	0.000e+00		0.000e+00
1.0e+14	0.000e+00		0.000e+00
1.0e+15	0.000e+00		0.000e+00
1.0e+16	0.000e+00		0.000e+00
1.0e+17	0.000e+00		0.000e+00
1.0e+18	0.000e+00		0.000e+00
1.0e+19	0.000e+00		0.000e+00
1.0e+20	0.000e+00		0.000e+00


In [56]:
m, n = 3, 2
np.indices((m, n)).reshape(2, -1).T

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [2, 0],
       [2, 1]])

In [ ]:
import numpy as np

arr = np.array([[0, 1]])  # shape (1,2)
b = np.broadcast_to(arr, (5, 2))  # shape (5,2)

b[0, 0] = 99  # attempt to write

ValueError: assignment destination is read-only

In [62]:
pair_list = [(0, 1)]
arr = np.broadcast_to(pair_list, (3, 2))
arr

array([[0, 1],
       [0, 1],
       [0, 1]])

In [65]:
[(0, 0)] == [(0, 0)]

True

In [68]:
def hi(a, b, **kwargs):
    return kwargs


hi(a='what', derp=33, boop=90, b=40, ac=100) | dict(mega=22)

{'derp': 33, 'boop': 90, 'ac': 100, 'mega': 22}

In [ ]:
@njit
def hi():
    return (sorted(range(100), key=lambda x: np.sin(x)))[::-1]


hi()

[33,
 77,
 58,
 14,
 8,
 52,
 96,
 83,
 39,
 27,
 71,
 64,
 20,
 2,
 46,
 90,
 89,
 45,
 1,
 21,
 65,
 70,
 26,
 40,
 84,
 95,
 51,
 7,
 15,
 59,
 76,
 32,
 34,
 78,
 57,
 13,
 9,
 53,
 97,
 82,
 38,
 28,
 72,
 63,
 19,
 3,
 47,
 91,
 88,
 44,
 0,
 22,
 66,
 69,
 25,
 41,
 85,
 94,
 50,
 6,
 16,
 60,
 75,
 31,
 35,
 79,
 56,
 12,
 10,
 54,
 98,
 81,
 37,
 29,
 73,
 62,
 18,
 4,
 48,
 92,
 87,
 43,
 23,
 67,
 68,
 24,
 42,
 86,
 93,
 49,
 5,
 17,
 61,
 74,
 30,
 36,
 80,
 99,
 55,
 11]

In [ ]:
@njit
def hi():
    return np.empty((1, 2), dtype=nb.int64)


hi()

array([[0, 0]])

In [ ]:
@njit
def hi():
    derp = []

    def do(x):
        derp.append(x)

    for i in range(5):
        do(i)
    return derp


hi()

[0, 1, 2, 3, 4]

In [ ]:
from numba.typed import List


@njit
def hi(a):
    for i, aa in enumerate(a):
        if i == 0:
            assert list(aa) == [(0, 1), (4, 5)]
        for j, aaa in enumerate(aa):
            print(i, j, aaa)
            print(isinstance(aaa, tuple))


hi(List([List([(0, 1), (4, 5)]), List([(3, 2)])]))

0 0 (0, 1)
True
0 1 (4, 5)
True
1 0 (3, 2)
True


In [92]:
List((3, 5) for i in range(5))

ListType[UniTuple(int64 x 2)]([(3, 5), (3, 5), (3, 5), (3, 5), (3, 5)])

In [ ]:
@njit
def hi():
    a = np.zeros((5, 2, 2), dtype=np.int64)
    a[0, 0] = 4, 6
    a[0, 1] = 5, 2
    return a


hi()

array([[[4, 6],
        [5, 2]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [105]:
len(np.zeros((3, 4)))

3

In [ ]:
np.round(0.5)

np.float64(0.0)

In [ ]:
null_njit = njit(inline='always')(lambda *args: None)

In [116]:
null_njit(5, 5, 2)

TypeError: too many arguments: expected 2, got 3

In [117]:
np.clip(4.0, 1, 2)

np.float64(2.0)

In [118]:
a = np.arange(5)
b = a[:3]

In [122]:
b[2] = 100
a, b

(array([  0,   1, 100,   3,   4]), array([  0,   1, 100]))

In [ ]:
@njit
def hi(a):
    (x0, y0), (x1, y1) = a
    return x0, y0, x1, y1


hi(np.asarray([[1, 2], [3, 4]]))

(1, 2, 3, 4)

In [ ]:
def diamond_transform(img):
    """
    Applies the diamond edge transformation using plain NumPy vectorization.

    Mapping Logic derived from user example:
    - Horizontal Diffs at (y, x): u = y + x, v = x - y + (H - 1)
    - Vertical Diffs at (y, x):   u = y + x, v = x - y + (H - 1) - 1
    """
    # Ensure input is an array
    img = np.asarray(img)
    H, W = img.shape

    # 1. Calculate Differences (Vectorized)
    # diff_h: difference between column x and x+1. Shape (H, W-1)
    diff_h = np.abs(img[:, :-1] - img[:, 1:])

    # diff_v: difference between row y and y+1. Shape (H-1, W)
    diff_v = np.abs(img[:-1, :] - img[1:, :])

    # 2. Generate Coordinate Grids
    # Indices for Horizontal Diffs
    # rows_h ranges 0..H-1, cols_h ranges 0..W-2
    rows_h, cols_h = np.indices((H, W - 1))

    # Indices for Vertical Diffs
    # rows_v ranges 0..H-2, cols_v ranges 0..W-1
    rows_v, cols_v = np.indices((H - 1, W))

    # 3. Calculate Target Coordinates
    # Offset ensures the minimum v-index starts at 0.
    offset = H - 1

    # Map Horizontal Diffs
    u_h = rows_h + cols_h
    v_h = cols_h - rows_h + offset

    # Map Vertical Diffs
    # Vertical diffs sit "to the left" of the corresponding horizontal diff in the rotated grid
    u_v = rows_v + cols_v
    v_v = cols_v - rows_v + offset - 1

    # 4. Create Output Canvas
    # The output shape is determined by the max range of u and v.
    # Max u = (H-1) + (W-1) - 1 approx. Exact size is H + W - 2.
    out_size = H + W - 2

    # Handle edge case for very small images (1x1)
    if out_size <= 0:
        return np.zeros((0, 0), dtype=img.dtype)

    canvas = np.zeros((out_size, out_size), dtype=img.dtype)

    # 5. Assign Values (Vectorized Advanced Indexing)
    # We check bounds just in case, though the math guarantees fit for H,W > 1
    valid_h = (u_h < out_size) & (v_h < out_size) & (v_h >= 0)
    canvas[u_h[valid_h], v_h[valid_h]] = diff_h[valid_h]

    valid_v = (u_v < out_size) & (v_v < out_size) & (v_v >= 0)
    canvas[u_v[valid_v], v_v[valid_v]] = diff_v[valid_v]

    return canvas


a = np.asarray(
    [
        [1, 2, 4],
        [8, 16, 32],
        [64, 128, 256],
    ]
)
diamond_transform(a)

array([[  0,   7,   1,   0],
       [ 56,   8,  14,   2],
       [ 64, 112,  16,  28],
       [  0, 128, 224,   0]])

In [ ]:
b = np.asarray(
    [
        [0, 7, 1, 0],
        [56, 8, 14, 2],
        [64, 112, 16, 28],
        [0, 128, 224, 0],
    ]
)

In [ ]:
from numpy.random import SeedSequence, default_rng

ss = SeedSequence(12345)
child_seeds = ss.spawn(10)  # Spawns 10 child SeedSequences
rng = default_rng(ss)  # Using the parent SeedSequence
streams = [default_rng(s) for s in child_seeds]

In [141]:
master_seed = 0
ss = np.random.SeedSequence(master_seed)

# Generate N independent 32-bit seeds
N = 4
child_seeds = ss.generate_state(N, dtype=np.uint32)
child_seeds

array([2968811710, 3677149159,  745650761, 2884920346], dtype=uint32)

In [3]:
import numpy as np
from PIL import Image
from hilbertcurve.hilbertcurve import HilbertCurve
import colour

arr = np.arange(256, dtype=np.uint8)
# Create the meshgrid for R, G, B
R, G, B = np.meshgrid(arr, arr, arr, indexing='ij')
# Stack and reshape to a flat list of (N, 3)
rgb_flat = np.stack((R, G, B), axis=-1).reshape(-1, 3)
is_gray = (rgb_flat[..., 0] == rgb_flat[..., 1]) & (rgb_flat[..., 1] == rgb_flat[..., 2])

# 2. Randomize (Shuffle) first
# This ensures that within similar hues, L and C are random
# print("Shuffling colors...")
# np.random.shuffle(rgb_flat)

# 3. Convert to OKLCH Hue
print("Converting to OKLCH (this may take a moment)...")
# Normalize to 0-1 for conversion
rgb_norm = rgb_flat.astype(np.float64) / 255.0

# Convert sRGB -> Linear sRGB -> XYZ -> OKLAB -> OKLCH
# Using colour-science library for accuracy
# We process in batches to save RAM if necessary, but 16M fits in 16GB RAM usually
XYZ = colour.sRGB_to_XYZ(rgb_norm)
# Note: colour.XYZ_to_Oklab assumes D65 XYZ
OKLAB = colour.XYZ_to_Oklab(XYZ)
OKLCH = colour.Oklab_to_Oklch(OKLAB)
OKLCH[..., 2][is_gray] = np.nan

Converting to OKLCH (this may take a moment)...


In [6]:
np.isnan(OKLCH).sum()

256

In [13]:
np.nan_to_num(OKLCH[..., 0]).max()

1.000001735347926

In [21]:
np.nan_to_num(OKLCH[..., 2]).min(), np.nan_to_num(OKLCH[..., 2]).max()

(0.0, 359.99999837897042)

In [22]:
hsv = mpl.colors.rgb_to_hsv(rgb_norm)

In [23]:
hsv[..., 0].min(), hsv[..., 0].max()

(0.0, 0.99934640522875817)

In [30]:
np.random.shuffle(color_walks['h'])

In [31]:
arr = color_walks['h']
keys = np.random.random(len(arr))
shuffled = arr[np.lexsort([keys])]

In [ ]:
@njit(parallel=True)
def copy_colors_using_walk(colors_walk, canvas_shape, walk):
    m, n = canvas_shape
    p = m * n
    assert len(colors_walk) == p
    assert len(walk) == p
    output = np.empty((m, n) + colors_walk.shape[1:], dtype=colors_walk.dtype)
    image1 = output.reshape((p,) + colors_walk.shape[1:])
    for i in prange(p):
        image1[walk[i]] = colors_walk[i]
    return output

In [7]:
copy_colors_using_walk(
    # np.asarray([[255, 0, 0], [0, 255, 0], [0, 0, 255], [255, 255, 0]]),
    np.asarray([0, 10, 20, 30]),
    (2, 2),
    np.asarray([0, 1, 2, 3]),
)

array([[ 0, 10],
       [20, 30]])

In [8]:
def make_all_rectangles(max_side_length):
    rectangles = {}
    for height in range(1, max_side_length + 1):
        for width in range(1, max_side_length + 1):
            rectangles.setdefault(height * width, []).append((height, width))
    return [rectangles for size, rectangles in sorted(rectangles.items())]

In [12]:
sum(len(x) for x in make_all_rectangles(2**5))

1024

In [196]:
my_spec = (
    ('data', nb.int64[:]),
    ('other', nb.int64[:]),
)


@jitclass(my_spec)
class MyClass:
    def __init__(self, data, other):
        self.data = np.asarray(data, dtype=np.int64)
        self.other = np.asarray(other, dtype=np.int64)

    def sum(self):
        print("MyClass original")
        return self.data.sum()

    def head(self):
        return self.data[0], self.other[0]

    def calc(self, x):
        if x <= 0:
            return 0
        return self.calc(x - 1) + self.sum()


my = MyClass(data=[4], other=[0])
my.calc(1)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
Failed in nopython mode pipeline (step: nopython frontend)
compiler re-entrant to the same function signature
During: Pass nopython_type_inference
- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'calc') for instance.jitclass.MyClass#157705d30<data:array(int64, 1d, A),other:array(int64, 1d, A)>)
During: typing of call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/1606003941.py (23)


File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/1606003941.py", line 23:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference
- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'calc') for instance.jitclass.MyClass#157705d30<data:array(int64, 1d, A),other:array(int64, 1d, A)>)
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [19]:
np.dtype(np.int64)

dtype('int64')

In [ ]:
np.int64

numpy.int64

In [21]:
np.dtype('float32')

dtype('float32')

In [22]:
np.array([1, 2, 3], dtype=np.int64).dtype

dtype('int64')

In [23]:
import numpy as np

dt = np.dtype([('x', 'f4'), ('y', 'f4'), ('z', 'f4')])
arr = np.zeros(1000000, dtype=dt)

# Access field
arr['x'] += 1.0

In [24]:
arr

array([( 1.,  0.,  0.), ( 1.,  0.,  0.), ( 1.,  0.,  0.), ...,
       ( 1.,  0.,  0.), ( 1.,  0.,  0.), ( 1.,  0.,  0.)],
      dtype=[('x', '<f4'), ('y', '<f4'), ('z', '<f4')])

In [ ]:
arr['x'] += np.array([1, 2, 3])

ValueError: operands could not be broadcast together with shapes (1000000,) (3,) (1000000,) 

In [ ]:
arr[:, 0] += np.array([1, 2, 3])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
@njit
def hello(type):
    return np.ones((3,), dtype=type)


hello(np.int64)

array([1, 1, 1])

In [33]:
nb.from_dtype(np.int64) is nb.int64

True

In [ ]:
record_type = np.dtype([("ival", np.int32), ("fval", np.float64)], align=True)


def f(rec):
    value = 2.5
    rec[0].ival = int(value)
    rec[0].fval = value
    return rec


arr = np.ones(1, dtype=record_type)

cfunc = njit(f)

# Works
print(cfunc(arr))

# Does not work
print(f(arr))

[(2,  2.5)]


AttributeError: 'numpy.void' object has no attribute 'ival'

In [53]:
arr[0]['ival'] = 4
ival = arr[0]
ival

(4,  2.5)

In [ ]:
my_spec = (
    ('data', nb.int64[:]),
    ('other', nb.int64[:]),
)


@jitclass(my_spec)
class MyClass:
    def __init__(self, data, other):
        self.data = np.asarray(data, dtype=np.int64)
        self.other = np.asarray(other, dtype=np.int64)

    def sum(self):
        print("MyClass original")
        return self.data.sum()

    def head(self):
        return self.data[0], self.other[0]


my = MyClass(data=[4], other=[0])


@njit
def hi(func):
    return func()


hi(my.sum)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
During: typing of argument at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_11351/3946574137.py (23)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_11351/3946574137.py", line 23:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference 

This error may have been caused by the following argument(s):
- argument 0: Cannot determine Numba type of <class 'method'>


In [ ]:
@njit
def hi():
    return np.linalg.norm(np.asarray([3.0, 4.0])), np.linalg.norm((4, 5))


hi()

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function norm at 0x1163140e0>) found for signature:
 
 >>> norm(Tuple(Literal[int](4), Literal[int](5)))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'norm_impl': File: numba/np/linalg.py: Line 2441.
    With argument(s): '(UniTuple(int64 x 2))':
   Rejected as the implementation raised a specific error:
     TypingError: np.linalg.norm() only supported for array types 
  raised from /Users/michaelyu/anaconda3/lib/python3.12/site-packages/numba/np/linalg.py:980

During: resolving callee type: Function(<function norm at 0x1163140e0>)
During: typing of call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_11351/3926837172.py (3)


File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_11351/3926837172.py", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
@njit
def hi():
    return np.asarray([1, 2, 3])[np.asarray([0, 2])]


hi()

array([1, 3])

In [8]:
a = np.float64(0.9999999999999999)
a

0.99999999999999989

In [9]:
x = np.float64(1e308)
x

1e+308

In [13]:
a = 0.9999999999999999
x = 1e308
print(a * x == x)
print(a * x, x)

False
9.999999999999998e+307 1e+308


In [ ]:
@njit
def hi():
    return np.inf == np.inf


hi()

True

In [20]:
@njit
def weighted_random_index(weights):
    """
    Select index i with probability proportional to weights[i].
    Mutates `weights` in-place into prefix sums.
    Uses searchsorted with side='right' so we pick the smallest i with prefix[i] > r.
    """
    n = weights.shape[0]
    if n == 0:
        raise ValueError("weights must be non-empty")

    # build prefix sums in-place
    for i in range(1, n):
        weights[i] += weights[i - 1]

    total = weights[n - 1]
    if total <= 0.0:
        raise ValueError("sum of weights must be positive")

    # sample r in [0, total)
    r = np.random.random() * total

    # return smallest i with prefix[i] > r — matches half-open intervals [low, high)
    return np.searchsorted(weights, r, side='right')

In [75]:
weighted_random_index(np.asarray([0.0, 0.0, 1.0, 1.0, 0.0]))

2

In [ ]:
@njit
def hi(weights, target_weight):
    for i in range(weights.shape[0]):
        weights[i] = weights[i] == target_weight
    return weights


hi(np.asarray([0.0, 1.0, 2.0, 1.0]).astype(int), 1.0)

array([0, 1, 0, 1])

In [ ]:
@njit
def hi(something):
    if something == 'hello':
        print('hi!')
    else:
        print(something**2)


hi('hello')

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function pow>) found for signature:
 
 >>> pow(unicode_type, Literal[int](2))
 
There are 6 candidate implementations:
  - Of which 4 did not match due to:
  Overload of function 'pow': File: <numerous>: Line N/A.
    With argument(s): '(unicode_type, int64)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'pow': File: unknown: Line unknown.
    With argument(s): '(unicode_type, int64)':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, int32) -> float32
    * (float32, int64) -> float32
    * (float32, uint64) -> float32
    * (float64, int32) -> float64
    * (float64, int64) -> float64
    * (float64, uint64) -> float64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/2794361672.py (6)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/2794361672.py", line 6:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
@njit
def create_my_class():
    my_spec = (
        ('data', nb.int64[:]),
        ('other', nb.int64[:]),
    )

    # @jitclass(my_spec)
    class MyClass:
        def __init__(self, data, other):
            self.data = np.asarray(data, dtype=np.int64)
            self.other = np.asarray(other, dtype=np.int64)

        def sum(self):
            print("MyClass original")
            return self.data.sum()

        def head(self):
            return self.data[0], self.other[0]

    return MyClass


MyClass = create_my_class()
my = MyClass(data=[4], other=[0])


@njit
def hi(func):
    return func()


hi(my.sum)

UnsupportedBytecodeError: Use of unsupported opcode (LOAD_BUILD_CLASS) found. Raised from /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/888357026.py (9)

In [ ]:
import numba
import numpy as np
import time


# -------------------------
# Inline-aware decorator (fixed)
# -------------------------
def njit_inline(use_inline=True):
    # decorator factory
    def decorator(func):
        if use_inline:
            return numba.njit(inline='always')(func)
        else:
            return numba.njit(func)

    return decorator


# -------------------------
# Example helpers
# -------------------------
def define_helpers(use_inline=True):
    @njit_inline(use_inline)
    def helper1(x):
        return x * x + 1

    @njit_inline(use_inline)
    def helper2(x):
        return helper1(x) + np.sin(x)

    @njit_inline(use_inline)
    def helper3(x):
        return helper2(x) + np.cos(x)

    return [helper1, helper2, helper3]


# -------------------------
# Benchmarking wrapper
# -------------------------
def benchmark_helpers(helpers, n_iter=10_000_000):
    arr = np.linspace(0, 10, n_iter, dtype=np.float64)
    results = []

    for h in helpers:
        # Top-level loop calling the helper
        @numba.njit
        def hot_loop(arr):
            s = 0.0
            for x in arr:
                s += h(x)
            return s

        # Warmup (trigger compilation)
        hot_loop(arr[:10])

        # Timing
        start = time.perf_counter()
        hot_loop(arr)
        elapsed = time.perf_counter() - start

        results.append((h.__name__, elapsed))

    return results


# -------------------------
# Run benchmark
# -------------------------
def run_benchmark():
    for use_inline in [True, False]:
        helpers = define_helpers(use_inline)
        print(f"\n=== USE_INLINE={use_inline} ===")
        results = benchmark_helpers(helpers)
        for name, t in results:
            print(f"{name}: {t:.4f} seconds")


# -------------------------
# Execute
# -------------------------
if __name__ == "__main__":
    run_benchmark()


=== USE_INLINE=True ===
helper1: 0.0146 seconds
helper2: 0.0959 seconds
helper3: 0.1034 seconds

=== USE_INLINE=False ===
helper1: 0.0148 seconds
helper2: 0.0958 seconds
helper3: 0.1037 seconds


In [ ]:
from numbers import Integral


def hi():
    return issubclass(np.int64, np.integer)


hi()

True

In [191]:
type(np.int64)

type

In [194]:
nb.bool_ is nb.boolean

True

In [195]:
np.bool_ is np.boolean

AttributeError: module 'numpy' has no attribute 'boolean'

In [ ]:
def create_my_class():
    my_spec = (('data', nb.int64[:]),)

    @jitclass(my_spec)
    class MyClass:
        def __init__(self, data):
            self.data = data

        def __getitem__(self, i):
            return self.data[i]

        def __delitem__(self, i):
            self.data[i] -= 1

    return MyClass


MyClass = create_my_class()


@njit
def hi():
    my = MyClass(data=np.asarray([4, 5, 6]))
    print(my[0])
    del my[1]
    del my[2]
    del my[2]
    print(my.data)


hi()

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function delitem>) found for signature:
 
 >>> delitem(instance.jitclass.MyClass#15ba68dd0<data:array(int64, 1d, A)>, Literal[int](1))
 
There are 10 candidate implementations:
    - Of which 10 did not match due to:
    Overload of function 'delitem': File: <numerous>: Line N/A.
      With argument(s): '(instance.jitclass.MyClass#15ba68dd0<data:array(int64, 1d, A)>, int64)':
     No match.

During: typing of delitem at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/1851750867.py (26)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_7267/1851750867.py", line 26:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
def create_my_class():
    my_spec = (('data', nb.int64[:, :]),)

    @jitclass(my_spec)
    class MyClass:
        def __init__(self, data):
            self.data = data

        def __setitem__(self, i, tup):
            self.data[i] = tup

    return MyClass


MyClass = create_my_class()


@njit
def hi():
    my = MyClass(np.asarray([[1, 2, 3], [4, 5, 6]]))
    my[0] = (7, 8, 9)
    print(my.data)


hi()

[[7 8 9]
 [4 5 6]]


In [254]:
np.random.lognormal(-1e1, 0.01)

4.5262891765233477e-05

In [ ]:
@njit
def hi():
    var = 4

    def do():
        nonlocal var
        var += 1

    do()
    do()
    return var


hi()

6

In [ ]:
@njit
def hi(a, b):
    return np.isclose(a, b, rtol=1e-9, atol=1e-12)


hi(10, 10.0000001)

False

In [ ]:
@njit
def hi(label_type):
    return label_type(np.iinfo(label_type).max)


hi(np.float64)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'numpy.iinfo'>) found for signature:
 
 >>> iinfo(class(float64))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'ol_np_iinfo': File: numba/np/old_arraymath.py: Line 4073.
    With argument(s): '(class(float64))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Invalid use of none with parameters (class(float64))
   No type info available for none as a callable.
   During: resolving callee type: none
   During: typing of call at /Users/michaelyu/anaconda3/lib/python3.12/site-packages/numba/np/old_arraymath.py (4078)
   
   
   File "../../../../../../../../anaconda3/lib/python3.12/site-packages/numba/np/old_arraymath.py", line 4078:
       def impl(int_type):
           return fn(int_type)
           ^
   
   During: Pass nopython_type_inference
  raised from /Users/michaelyu/anaconda3/lib/python3.12/site-packages/numba/core/typeinfer.py:1074

During: resolving callee type: Function(<class 'numpy.iinfo'>)
During: typing of call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_54535/719601565.py (3)


File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_54535/719601565.py", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
def program(seed):
    ss = np.random.SeedSequence(seed)
    (child_seed_sequence,) = ss.spawn(1)
    rng = np.random.default_rng(child_seed_sequence)
    print(rng.integers(1000000))

    ss = np.random.SeedSequence(seed)
    child_seed_sequence, _ = ss.spawn(2)
    rng = np.random.default_rng(child_seed_sequence)
    print(rng.integers(1000000))

    ss = np.random.SeedSequence(seed)
    child_seed_sequence, _, _ = ss.spawn(3)
    rng = np.random.default_rng(child_seed_sequence)
    print(rng.integers(1000000))


program(0)

802237
802237
802237


In [ ]:
a = np.arange(2**24)
t0 = time.time()
# np.random.shuffle(a)
a[np.random.permutation(np.arange(a.size))]
print(time.time() - t0)

1.249664068222046


In [ ]:
rng = np.random.default_rng(0)

a = np.arange(2**24)
t0 = time.time()
# rng.shuffle(a)
a[rng.permutation(np.arange(a.size))]
print(time.time() - t0)

1.2190470695495605


In [ ]:
rng = np.random.default_rng(0)


@njit
def shuffle(a):
    # np.random.shuffle(a)
    return a[np.random.permutation(np.arange(a.size))]


shuffle(np.arange((2)))

a = np.arange(2**24)
t0 = time.time()
shuffle(a)
print(time.time() - t0)

1.303689956665039


In [ ]:
rng = np.random.default_rng(0)


@njit
def shuffle(rng, a):
    # rng.shuffle(a)
    return a[rng.permutation(np.arange(a.size))]


shuffle(rng, np.arange((2)))

a = np.arange(2**24)
t0 = time.time()
shuffle(rng, a)
print(time.time() - t0)

2.8071439266204834


In [12]:
side = 4096
rng = np.random.default_rng(0)
empty = create_not_connected_2d_grid((side, side), 'four')
# empty.randomize_neighbors_orders()
empty.randomize_neighbors_orders()

In [86]:
@njit
def weighted_random_index(rng, weights):
    """
    Select index i with probability proportional to weights[i].
    Mutates `weights` in-place into prefix sums.
    Uses searchsorted with side='right' so we pick the smallest i with prefix[i] > r.
    """
    n = len(weights)
    if n == 0:
        raise ValueError("weights must be non-empty")

    # build prefix sums in-place
    for i in range(1, n):
        weights[i] += weights[i - 1]

    total = weights[n - 1]
    if total <= 0.0:
        raise ValueError("sum of weights must be positive")

    # sample r in [0, total)
    r = rng.random() * total

    # return smallest i with prefix[i] > r — matches half-open intervals [low, high)
    return np.searchsorted(weights, r, side='right')


@njit
def custom_weighted_random_index(rng, weights, power):
    if power == 0.0:
        return rng.integers(0, len(weights))
    if np.isfinite(power):
        weights **= power
        return weighted_random_index(rng, weights)
    else:
        if power == np.inf:
            target_weight = weights.max()
        elif power == -np.inf:
            target_weight = weights.min()
        else:
            raise ValueError("power must be finite or infinite")
        for i in range(weights.shape[0]):
            weights[i] = weights[i] == target_weight
        return weighted_random_index(rng, weights)

In [ ]:
int_dtype = np.int64


@njit
def top_level(length):
    width = 8
    size = length * width
    buffer = np.empty(width, dtype=int_dtype)
    a = np.arange(size - 1, -1, -1).reshape((length, width))
    out = np.empty(length, dtype=int_dtype)
    for i in range(length):

        jj = np.argsort(a[i])
        a[i] = a[i, jj]

        buffer[0] = a[i, 0]
        for j in range(1, width):
            buffer[j] = buffer[j - 1] + a[i, j]
        r = np.random.random() * buffer[-1]
        out[i] = np.searchsorted(buffer, r, side='right')


@njit
def with_rng(rng, length):
    width = 8
    size = length * width
    buffer = np.empty(width, dtype=int_dtype)
    a = np.arange(size - 1, -1, -1).reshape((length, width))
    out = np.empty(length, dtype=int_dtype)
    for i in range(length):

        jj = np.argsort(a[i])
        a[i] = a[i, jj]

        buffer[0] = a[i, 0]
        for j in range(1, width):
            buffer[j] = buffer[j - 1] + a[i, j]
        r = rng.random() * buffer[-1]
        out[i] = np.searchsorted(buffer, r, side='right')


rng = np.random.default_rng(0)
top_level(2)
with_rng(rng, 2)

length = 4096**2

t0 = time.time()
top_level(length)
print(time.time() - t0)

t0 = time.time()
with_rng(rng, length)
print(time.time() - t0)

18.442084312438965
19.526232957839966


In [ ]:
np.moveaxis(np.mgrid[0:4, 0:4, 0:4], 0, -1).reshape(4 * 4 * 4, 3)

array([[0, 0, 0],
       [0, 0, 1],
       [0, 0, 2],
       [0, 0, 3],
       [0, 1, 0],
       [0, 1, 1],
       [0, 1, 2],
       [0, 1, 3],
       [0, 2, 0],
       [0, 2, 1],
       [0, 2, 2],
       [0, 2, 3],
       [0, 3, 0],
       [0, 3, 1],
       [0, 3, 2],
       [0, 3, 3],
       [1, 0, 0],
       [1, 0, 1],
       [1, 0, 2],
       [1, 0, 3],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 2],
       [1, 1, 3],
       [1, 2, 0],
       [1, 2, 1],
       [1, 2, 2],
       [1, 2, 3],
       [1, 3, 0],
       [1, 3, 1],
       [1, 3, 2],
       [1, 3, 3],
       [2, 0, 0],
       [2, 0, 1],
       [2, 0, 2],
       [2, 0, 3],
       [2, 1, 0],
       [2, 1, 1],
       [2, 1, 2],
       [2, 1, 3],
       [2, 2, 0],
       [2, 2, 1],
       [2, 2, 2],
       [2, 2, 3],
       [2, 3, 0],
       [2, 3, 1],
       [2, 3, 2],
       [2, 3, 3],
       [3, 0, 0],
       [3, 0, 1],
       [3, 0, 2],
       [3, 0, 3],
       [3, 1, 0],
       [3, 1, 1],
       [3, 1, 2],
       [3,

In [ ]:
@njit
def hi(a):
    return np.prod(a)


hi(np.asarray((4, 5, 6)))

120

In [26]:
np.prod((3, 5, 6))

90

In [ ]:
@njit
def hi(a):
    a **= 2


hi(np.asarray([4]))

In [84]:
color_bits = 8
colors_size = 2 ** (color_bits * 3)
all_rgb_grid = np.mgrid[0 : 2**color_bits, 0 : 2**color_bits, 0 : 2**color_bits]
rgb_colors = np.moveaxis(all_rgb_grid, 0, -1).reshape(colors_size, 3) * (256 // 2**color_bits)
rng = np.random.default_rng(0)
t0 = time.time()
# rng.shuffle(rgb_colors)

# rgb_colors = rng.permutation(rgb_colors)

# keys = np.random.random(len(rgb_colors))
# rng.shuffle(keys)
# rgb_colors = rgb_colors[np.lexsort([keys])]

indices = np.arange(len(rgb_colors))
# rng.shuffle(indices)

# indices = rng.permutation(indices)
# indices = np.random.permutation(indices)

rgb_colors = rgb_colors[indices]

print(time.time() - t0)
rgb_colors

4.720322132110596


array([[ 21,  40,  73],
       [209, 140, 198],
       [ 55, 165,  82],
       ..., 
       [111, 185, 176],
       [ 37,  38, 142],
       [ 83, 253, 165]])

In [35]:
mpl.colors.rgb_to_hsv(np.asarray([-0.2, 1.0, 1.0]))

ValueError: Input array must be in the range [0, 1]. Found a minimum value of -0.2

In [72]:
color_bits = 2
colors_size = 2 ** (color_bits * 3)
all_rgb_grid = np.mgrid[0 : 2**color_bits, 0 : 2**color_bits, 0 : 2**color_bits]
rgb_colors = np.moveaxis(all_rgb_grid, 0, -1).reshape(colors_size, 3)  # * (256 // 2**color_bits)
# rgb_colors
reorder_indices = np.lexsort(np.stack([rgb_colors[..., i] for i in [1, 2, 0]]))
rgb_colors[reorder_indices]

array([[0, 0, 0],
       [0, 1, 0],
       [0, 2, 0],
       [0, 3, 0],
       [0, 0, 1],
       [0, 1, 1],
       [0, 2, 1],
       [0, 3, 1],
       [0, 0, 2],
       [0, 1, 2],
       [0, 2, 2],
       [0, 3, 2],
       [0, 0, 3],
       [0, 1, 3],
       [0, 2, 3],
       [0, 3, 3],
       [1, 0, 0],
       [1, 1, 0],
       [1, 2, 0],
       [1, 3, 0],
       [1, 0, 1],
       [1, 1, 1],
       [1, 2, 1],
       [1, 3, 1],
       [1, 0, 2],
       [1, 1, 2],
       [1, 2, 2],
       [1, 3, 2],
       [1, 0, 3],
       [1, 1, 3],
       [1, 2, 3],
       [1, 3, 3],
       [2, 0, 0],
       [2, 1, 0],
       [2, 2, 0],
       [2, 3, 0],
       [2, 0, 1],
       [2, 1, 1],
       [2, 2, 1],
       [2, 3, 1],
       [2, 0, 2],
       [2, 1, 2],
       [2, 2, 2],
       [2, 3, 2],
       [2, 0, 3],
       [2, 1, 3],
       [2, 2, 3],
       [2, 3, 3],
       [3, 0, 0],
       [3, 1, 0],
       [3, 2, 0],
       [3, 3, 0],
       [3, 0, 1],
       [3, 1, 1],
       [3, 2, 1],
       [3,

In [95]:
my_spec = (
    ('data', nb.float64[:]),
    ('rtol', nb.optional(nb.float64)),
    ('atol', nb.optional(nb.float64)),
)


@jitclass(my_spec)
class MyClass:
    def __init__(self, data, rtol=None, atol=None):
        self.data = np.asarray(data, dtype=np.float64)
        self.rtol = rtol
        self.atol = atol

    def sum(self):
        print("MyClass original")
        return self.data.sum()

    def query(self, x, rtol=None, atol=None):
        rtol = rtol if rtol is not None else self.rtol
        atol = atol if atol is not None else self.atol
        if rtol is not None:
            if atol is not None:
                return np.isclose(self.data, x, rtol=rtol, atol=atol)
        return False


my = MyClass(data=[4.0, 5.0], rtol=1e-5, atol=1e-8)
my.query(10.0)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function isclose at 0x116a034c0>) found for signature:

 >>> isclose(array(float64, 1d, A), float64, rtol=OptionalType(float64), atol=OptionalType(float64))

There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'isclose': File: numba/np/old_arraymath.py: Line 1124.
        With argument(s): '(array(float64, 1d, A), float64, rtol=OptionalType(float64), atol=OptionalType(float64))':
       Rejected as the implementation raised a specific error:
         TypingError: The third argument "rtol" must be a floating point
  raised from /Users/michaelyu/anaconda3/lib/python3.12/site-packages/numba/np/old_arraymath.py:1133

During: resolving callee type: Function(<function isclose at 0x116a034c0>)
During: typing of call at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/2907092704.py (24)


File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/2907092704.py", line 24:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference
- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.misc.ClassInstanceType'>, 'query') for instance.jitclass.MyClass#1668bc590<data:array(float64, 1d, A),rtol:OptionalType(float64),atol:OptionalType(float64)>)
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
from pytil.new_utility import isclose

my_spec = (
    ('data', nb.float64),
    ('rtol', nb.float64),
    ('atol', nb.float64),
)

NOT_GIVEN = -1.0


@jitclass(my_spec)
class MyClass:
    def __init__(self, data):
        self.data = data
        self.rtol = 1e-9
        self.atol = 0.0

    def set_tolerance(self, rtol, atol):
        self.rtol = rtol
        self.atol = atol

    def sum(self):
        print("MyClass original")
        return self.data.sum()

    def query(self, x, rtol=NOT_GIVEN, atol=NOT_GIVEN):
        rtol = rtol if rtol != NOT_GIVEN else self.rtol
        atol = atol if atol != NOT_GIVEN else self.atol
        return isclose(self.data, x, rel_tol=rtol, abs_tol=atol)


my = MyClass(data=5.0)
my.set_tolerance(0.0, 1.0)
my.query(6.0, 0.0, 0.5)

False

In [ ]:
@njit
def hi(x):
    return np.float64(x)


hi(2)

2.0

In [ ]:
@njit
def hi():
    return np.isclose(0.0, 0.0, rtol=-1.0, atol=-1.0)


hi()

False

In [ ]:
from numba import njit
import numpy as np

n = 5


@njit
def myOptimiser(x, y, opt1=None, opt2=None):
    if opt1 is None:
        if opt2 is None:
            return np.ones((n,)) + y
        else:
            return x + opt2
    else:
        if opt2 is None:
            return x * np.ones((n,)) + opt1
        return x - y


@njit
def call_opt(a, b):
    return myOptimiser(a, b, np.ones((n,)))


print(call_opt(10, 20))

[ 11.  11.  11.  11.  11.]


In [ ]:
@njit
def hi(x, y):
    return math.isclose(x, y)


hi(3, 0)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'isclose' of type Module(<module 'math' from '/Users/michaelyu/anaconda3/lib/python3.12/lib-dynload/math.cpython-312-darwin.so'>)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/2393861097.py", line 3:
<source missing, REPL/exec in use?>

During: typing of get attribute at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/2393861097.py (3)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/2393861097.py", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
@njit
def isclose(a, b, rel_tol=1e-9, abs_tol=0.0):
    return np.abs(a - b) <= np.maximum(rel_tol * np.maximum(np.abs(a), np.abs(b)), abs_tol)


isclose(np.asarray([0, 4]), 4)

array([False,  True], dtype=bool)

In [118]:
np.issubdtype(np.float64, np.integer)

False

In [ ]:
1.0 + 1.2e-16

1.0000000000000002

In [ ]:
@njit
def hi():
    return math.sqrt(-1.0)


hi()

nan

In [ ]:
sqrt = np.sqrt


@njit
def hi(n):
    x = 0.0
    for i in range(n):
        x += sqrt(sqrt(sqrt(float(i))))
    return x


hi(10)
t0 = time.time()
hi(1_000_000_000)
time.time() - t0

5.959423303604126

In [ ]:
ss = np.random.SeedSequence(0)
rng = np.random.default_rng(ss)
print(rng.random(size=5))
(ss0,) = ss.spawn(1)
rng0 = np.random.default_rng(ss0)
print(rng0.random(size=5))

[ 0.63696169  0.26978671  0.04097352  0.01652764  0.81327024]
[ 0.94293755  0.31633715  0.72234259  0.12560309  0.42297636]


In [ ]:
ss = np.random.SeedSequence(0)
# rng = np.random.default_rng(ss)
# print(rng.random(size=5))
(ss0,) = ss.spawn(1)
rng0 = np.random.default_rng(ss0)
print(rng0.random(size=5))

[ 0.94293755  0.31633715  0.72234259  0.12560309  0.42297636]


In [ ]:
@njit
def hi(rng):
    return rng.spawn(1)[0]


hi(np.random.default_rng(0))

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'spawn' of type NumPyRandomGeneratorType

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/3277942976.py", line 3:
<source missing, REPL/exec in use?>

During: typing of get attribute at /var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/3277942976.py (3)

File "../../../../../../../../../../var/folders/t6/_6f3y1xn7p30wrykck0s7nlc0000gn/T/ipykernel_25982/3277942976.py", line 3:
<source missing, REPL/exec in use?>

During: Pass nopython_type_inference

In [ ]:
from pytil.parameter_helper import AliasedValue

av = AliasedValue(4)
av

AliasedValue(4,)

In [ ]:
from pytil.parameter_helper import AliasedValues

avs = AliasedValues(
    ('param', 0),
    ('other', 1),
)
avs

(AliasedValue('param', 0), AliasedValue('other', 1))

In [23]:
isinstance(np.int64, object)

True

In [ ]:
from typing import get_origin

get_origin(int | float)

types.UnionType

In [ ]:
def hi(a, b, /, *, c, d):
    print(a, b, c, d)


hi(0, 1, c=2, d=3)

0 1 2 3


In [47]:
def hi(a, b, *, /, c, d):
    print(a, b, c, d)
hi(0, 1, c=2, d=3)

SyntaxError: / must be ahead of * (475792985.py, line 1)

In [ ]:
from enum import StrEnum


class MyEnum(StrEnum):
    Derp = 'd'
    Merp = 'm'
    Gerp = 'g'


issubclass(type(MyEnum.Derp), str)

True

In [54]:
np.random.default_rng(-1)

ValueError: expected non-negative integer

In [56]:
isinstance((4, 5), tuple[int, int])

TypeError: isinstance() argument 2 cannot be a parameterized generic

In [57]:
isinstance(None, list | None)

True

In [60]:
int('a0', 16)

160